server:
  servlet:
    encoding:
      force-response: true

jwt:
  token:
    secret: hello

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-db
    username: root
    password:

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  mustache:
    expose-request-attributes=true: